-- CREATE DATABASE `university-management`;

USE `university-management`;

CREATE TABLE USERS (
	id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    username VARCHAR(30) NOT NULL UNIQUE,
    password VARCHAR(255),
    first_name VARCHAR(30),
	last_name VARCHAR(30),
    date_of_birth DATE
);

CREATE TABLE USERS_ROLES (
    user_id CHAR(36) NOT NULL,
    role_name CHAR(36) NOT NULL
);

CREATE TABLE ROLES (
	name CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    description VARCHAR(30)
);

CREATE TABLE PERMISSIONS (
	name CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    description VARCHAR(30)
);

CREATE TABLE ROLES_PERMISSIONS (
    role_name CHAR(36) NOT NULL,
    permission_name CHAR(36) NOT NULL
);

SELECT * FROM USERS;
SELECT * FROM ROLES;
SELECT * FROM ROLES_PERMISSIONS;
SELECT * FROM PERMISSIONS;